import {
  Fleet,
  GameState,
  Planet,
  Player,
  PlayerTradeState,
  Resources,
  ShipType,
  Starbase,
  SystemTradeInfo,
  TradePolicy,
  TradeRoute,
} from './types';
import { getPlanetEffectiveBiome, getPlanetEcologyModifiers } from './terraforming';

export interface TradePolicyConfig {
  policy: TradePolicy;
  nameTr: string;
  descriptionTr: string;
  fuelRatio: number;
  crystalRatio: number;
  unityRatio: number;
  icon: string;
}

export const TRADE_POLICY_CONFIGS: Record<TradePolicy, TradePolicyConfig> = {
  energy_wealth: {
    policy: 'energy_wealth',
    nameTr: 'Enerji & Yakıt Geliri',
    descriptionTr: 'Ticaret Değerinin %100\'ünü doğrudan yakıt/enerji rezervine dönüştürür. Hızlı filolar ve askeri lojistik için idealdir.',
    fuelRatio: 1.0,
    crystalRatio: 0.0,
    unityRatio: 0.0,
    icon: '⚡',
  },
  consumer_benefits: {
    policy: 'consumer_benefits',
    nameTr: 'Tüketim & Refah Dağıtımı',
    descriptionTr: 'Ticaret Değerini %50 Yakıt ve %25 Kristale dönüştürür. Sanayi yatırımları ve ileri teknoloji üretimi için dengelidir.',
    fuelRatio: 0.5,
    crystalRatio: 0.25,
    unityRatio: 0.0,
    icon: '💎',
  },
  marketplace_of_ideas: {
    policy: 'marketplace_of_ideas',
    nameTr: 'Fikir Pazarı & Kültürel Ticaret',
    descriptionTr: 'Ticaret Değerini %50 Yakıt ve %15 Kültürel Birliğe (Unity) dönüştürür. Gelenekleri ve Yükseliş Ayrıcalıklarını hızlandırır.',
    fuelRatio: 0.5,
    crystalRatio: 0.0,
    unityRatio: 0.15,
    icon: '🏛️',
  },
};

/**
 * Calculates hourly Trade Value (TV) generated by a planet
 */
export function calculatePlanetTradeValue(
  planet: Planet,
  player?: Player,
  state?: GameState
): number {
  // Base TV: Homeworld generates 15, Colonies generate 8
  let tv = planet.isHomeworld ? 15 : 8;

  // Buildings TV contributions
  if (planet.buildings) {
    tv += (planet.buildings.ore_mine || 0) * 2;
    tv += (planet.buildings.crystal_synth || 0) * 4;
    tv += (planet.buildings.fuel_refinery || 0) * 3;
    tv += (planet.buildings.research_lab || 0) * 2;
  }

  // Planetary Specialization
  switch (planet.specialization) {
    case 'mining_hub':
      tv += 5;
      break;
    case 'tech_haven':
      tv += 5;
      break;
    case 'balanced':
      tv += 8;
      break;
    case 'military_bastion':
      tv += 2;
      break;
  }

  // Biome affinity for trade
  const effectiveBiome = getPlanetEffectiveBiome(planet);
  switch (effectiveBiome) {
    case 'ocean':
      tv *= 1.25; // Maritime trade ports
      break;
    case 'gaia':
      tv *= 1.35; // Flourishing paradisiacal trade hub
      break;
    case 'terran':
      tv *= 1.10;
      break;
    case 'desert':
      tv *= 0.95;
      break;
    case 'ice':
      tv *= 0.90;
      break;
    case 'volcanic':
      tv *= 0.85;
      break;
    case 'tomb':
      tv *= 0.70;
      break;
  }

  // Planetary Decisions modifiers
  if (planet.activeDecisions) {
    for (const dec of planet.activeDecisions) {
      if (dec.id === 'climate_domes') tv *= 1.15;
      if (dec.id === 'soil_enrichment') tv *= 1.10;
      if (dec.id === 'geothermal_core_drill') tv *= 1.05;
    }
  }

  // Commercial Pacts bonus: +10% per active pact partner
  if (player && player.commercialPacts && player.commercialPacts.length > 0) {
    tv *= (1 + player.commercialPacts.length * 0.10);
  }

  // Hyper Relay commercial freight corridor doctrine bonus (Phase 28)
  if (state?.hyperRelays && state.hyperRelays[planet.systemId] && !state.hyperRelays[planet.systemId].isConstructing) {
    const relay = state.hyperRelays[planet.systemId];
    if (relay.policy === 'commercial_freight') {
      tv *= 1.20;
    }
  }

  return Math.max(5, Math.round(tv));
}

/**
 * Finds shortest hyperlane path between origin and destination star systems
 */
export function findShortestTradeRoute(
  state: GameState,
  originSystemId: string,
  destinationSystemId: string
): string[] {
  if (originSystemId === destinationSystemId) {
    return [originSystemId];
  }

  // Subspace Gateway jump check (Phase 13):
  // If both origin and destination have active Gateways, trade routes jump instantly!
  if (
    state.gateways &&
    state.gateways[originSystemId]?.status === 'active' &&
    state.gateways[destinationSystemId]?.status === 'active'
  ) {
    return [originSystemId, destinationSystemId];
  }

  // Breadth-First Search (BFS) for shortest hyperlane hops
  const queue: { systemId: string; path: string[] }[] = [
    { systemId: originSystemId, path: [originSystemId] },
  ];
  const visited = new Set<string>([originSystemId]);

  while (queue.length > 0) {
    const current = queue.shift()!;
    if (current.systemId === destinationSystemId) {
      return current.path;
    }

    // Find connected systems via flight lanes
    for (const lane of state.map.lanes) {
      let neighborId: string | null = null;
      if (lane.fromSystemId === current.systemId) {
        neighborId = lane.toSystemId;
      } else if (lane.toSystemId === current.systemId) {
        neighborId = lane.fromSystemId;
      }

      if (neighborId && !visited.has(neighborId)) {
        visited.add(neighborId);
        queue.push({
          systemId: neighborId,
          path: [...current.path, neighborId],
        });
      }
    }
  }

  // Fallback: direct hop if disconnected
  return [originSystemId, destinationSystemId];
}

/**
 * Calculates trade protection stats provided by a starbase
 */
export function getStarbaseProtectionStats(starbase: Starbase): {
  protection: number;
  rangeHops: number;
} {
  let protection = 10;
  let rangeHops = 0;

  switch (starbase.tier) {
    case 'outpost':
      protection = 15;
      rangeHops = 0;
      break;
    case 'starbase':
      protection = 30;
      rangeHops = 1;
      break;
    case 'citadel':
      protection = 60;
      rangeHops = 2;
      break;
  }

  // Installed modules
  for (const mod of starbase.modules) {
    if (mod === 'defense_platform') {
      protection += 15;
    }
    if (mod === 'trade_hub') {
      protection += 10;
      rangeHops += 1;
    }
    if (mod === 'sensor_relay') {
      protection += 5;
    }
  }

  return { protection, rangeHops };
}

/**
 * Calculates piracy suppression value of a fleet
 */
export function calculateFleetPatrolSuppression(fleet: Fleet): number {
  const ships = fleet.ships || { scout: 0, transport: 0, fighter: 0, battleship: 0 };
  const fighterSuppression = (ships.fighter || 0) * 5;
  const battleshipSuppression = (ships.battleship || 0) * 15;
  const scoutSuppression = (ships.scout || 0) * 2;
  return fighterSuppression + battleshipSuppression + scoutSuppression;
}

/**
 * Finds all star systems within N hyperlane hops from a center system
 */
export function getSystemsWithinHops(
  state: GameState,
  centerSystemId: string,
  hops: number
): string[] {
  if (hops <= 0) return [centerSystemId];

  const results = new Set<string>([centerSystemId]);
  let currentLayer = new Set<string>([centerSystemId]);

  for (let h = 0; h < hops; h++) {
    const nextLayer = new Set<string>();
    for (const sysId of currentLayer) {
      for (const lane of state.map.lanes) {
        let neighbor: string | null = null;
        if (lane.fromSystemId === sysId) neighbor = lane.toSystemId;
        else if (lane.toSystemId === sysId) neighbor = lane.fromSystemId;

        if (neighbor && !results.has(neighbor)) {
          results.add(neighbor);
          nextLayer.add(neighbor);
        }
      }
    }
    currentLayer = nextLayer;
  }

  return Array.from(results);
}

/**
 * Main game engine tick for Galactic Trade Networks & Piracy
 */
export function updateTradeNetworks(state: GameState, deltaMs: number): void {
  state.tradeStates = state.tradeStates || {};
  state.systemTrade = state.systemTrade || {};

  // 1. Initialize or reset system trade metrics
  for (const sysId of Object.keys(state.map.systems)) {
    if (!state.systemTrade[sysId]) {
      state.systemTrade[sysId] = {
        systemId: sysId,
        tradeValuePassing: 0,
        tradeProtection: 0,
        piracyRisk: 0,
        piracySuppression: 0,
        piracySiphonedTV: 0,
        hasPirateFleetSpawned: false,
      };
    } else {
      state.systemTrade[sysId].tradeValuePassing = 0;
      state.systemTrade[sysId].tradeProtection = 0;
      state.systemTrade[sysId].piracySuppression = 0;
      state.systemTrade[sysId].piracySiphonedTV = 0;
    }
  }

  // 2. Project Starbase Trade Protection
  if (state.starbases) {
    for (const [sysId, starbase] of Object.entries(state.starbases)) {
      const { protection, rangeHops } = getStarbaseProtectionStats(starbase);
      const coveredSystems = getSystemsWithinHops(state, sysId, rangeHops);
      for (const coveredId of coveredSystems) {
        if (state.systemTrade[coveredId]) {
          state.systemTrade[coveredId].tradeProtection += protection;
        }
      }
    }
  }

  // 2b. Project Hyper Relay Trade Protection (Phase 28)
  if (state.hyperRelays) {
    for (const relay of Object.values(state.hyperRelays)) {
      if (!relay.isConstructing && state.systemTrade[relay.systemId]) {
        state.systemTrade[relay.systemId].tradeProtection += 100; // Complete immunity against piracy accumulation
      }
    }
  }

  // 3. Project Fleet Patrol Suppression
  if (state.fleets) {
    for (const fleet of Object.values(state.fleets)) {
      if (fleet.status === 'destroyed') continue;
      const suppression = calculateFleetPatrolSuppression(fleet);
      if (suppression <= 0) continue;

      if (fleet.mission === 'patrol') {
        // High suppression along entire patrol path
        for (const sysId of fleet.path) {
          if (state.systemTrade[sysId]) {
            state.systemTrade[sysId].piracySuppression += suppression;
          }
        }
      } else {
        // Any other fleet with warships provides local suppression in its current system
        const currentSysId =
          fleet.status === 'in_transit' && fleet.path[fleet.pathIndex]
            ? fleet.path[fleet.pathIndex]
            : fleet.targetSystemId;
        if (state.systemTrade[currentSysId]) {
          state.systemTrade[currentSysId].piracySuppression += Math.round(suppression * 0.5);
        }
      }
    }
  }

  // 4. Calculate Trade Routes & Aggregate Trade Value Passing Through Hyperlanes
  for (const [playerId, player] of Object.entries(state.players)) {
    let pTrade = state.tradeStates[playerId];
    if (!pTrade) {
      pTrade = {
        playerId,
        policy: player.tradePolicy || 'energy_wealth',
        routes: [],
        totalGeneratedTV: 0,
        totalCollectedTV: 0,
        totalLostTV: 0,
        commercialPacts: player.commercialPacts || [],
        lastUpdateMs: state.timeMs,
      };
      state.tradeStates[playerId] = pTrade;
    } else {
      pTrade.policy = player.tradePolicy || pTrade.policy || 'energy_wealth';
      pTrade.commercialPacts = player.commercialPacts || pTrade.commercialPacts || [];
    }

    const playerPlanets = Object.values(state.planets).filter((p) => p.ownerId === playerId);
    const homeworld = playerPlanets.find((p) => p.isHomeworld) || playerPlanets[0];
    if (!homeworld) continue;

    const routes: TradeRoute[] = [];
    let playerTotalGenerated = 0;

    for (const planet of playerPlanets) {
      const tv = calculatePlanetTradeValue(planet, player, state);
      playerTotalGenerated += tv;

      if (planet.id === homeworld.id) {
        // Capital consumes its own trade locally with 0 piracy exposure
        routes.push({
          originPlanetId: planet.id,
          originPlanetName: planet.name,
          originSystemId: planet.systemId,
          destinationPlanetId: homeworld.id,
          destinationPlanetName: homeworld.name,
          destinationSystemId: homeworld.systemId,
          pathSystemIds: [planet.systemId],
          tradeValue: tv,
          collectedValue: tv,
          piracyLoss: 0,
          active: true,
        });
        continue;
      }

      // Colony hyperlane route to capital
      const path = findShortestTradeRoute(state, planet.systemId, homeworld.systemId);

      // Route registers passing trade on all systems except the terminal capital
      for (let i = 0; i < path.length - 1; i++) {
        const sysId = path[i];
        if (state.systemTrade[sysId]) {
          state.systemTrade[sysId].tradeValuePassing += tv;
        }
      }

      routes.push({
        originPlanetId: planet.id,
        originPlanetName: planet.name,
        originSystemId: planet.systemId,
        destinationPlanetId: homeworld.id,
        destinationPlanetName: homeworld.name,
        destinationSystemId: homeworld.systemId,
        pathSystemIds: path,
        tradeValue: tv,
        collectedValue: tv, // Will be discounted after piracy check
        piracyLoss: 0,
        active: true,
      });
    }

    pTrade.routes = routes;
    pTrade.totalGeneratedTV = playerTotalGenerated;
  }

  // 5. Update Piracy Risk Dynamics and Siphoned Losses per System
  for (const sysTrade of Object.values(state.systemTrade)) {
    const passing = sysTrade.tradeValuePassing;
    const protection = sysTrade.tradeProtection;
    const suppression = sysTrade.piracySuppression;

    if (passing > protection) {
      // Unprotected trade generates piracy risk
      const deltaRisk =
        (passing - protection) * (deltaMs / 60000) * 0.8 -
        suppression * (deltaMs / 60000) * 1.5;
      sysTrade.piracyRisk = Math.min(100, Math.max(0, sysTrade.piracyRisk + deltaRisk));
    } else {
      // Protection suppresses piracy risk
      const decay = (protection + suppression - passing) * (deltaMs / 60000) * 1.2;
      sysTrade.piracyRisk = Math.max(0, sysTrade.piracyRisk - decay);
    }

    // Siphoned Trade Value in system
    if (sysTrade.piracyRisk > 5) {
      const siphonFactor = Math.min(0.60, (sysTrade.piracyRisk / 100) * 0.60);
      sysTrade.piracySiphonedTV = Math.round(passing * siphonFactor * 10) / 10;
    } else {
      sysTrade.piracySiphonedTV = 0;
    }

    // Pirate fleet spawn trigger when piracy reaches critical threshold (>= 95)
    if (sysTrade.piracyRisk >= 95 && passing >= 20 && !sysTrade.hasPirateFleetSpawned) {
      sysTrade.hasPirateFleetSpawned = true;
      const pirateFleetId = `pirate_raider_${state.nextId++}`;
      state.fleets[pirateFleetId] = {
        id: pirateFleetId,
        name: `Korsan Akıncı Filosu #${Math.floor(Math.random() * 900 + 100)}`,
        ownerId: 'pirate_faction',
        ships: { scout: 1, transport: 0, fighter: 4, battleship: 1 },
        cargo: { ore: 200, crystal: 100, fuel: 100 },
        originSystemId: sysTrade.systemId,
        targetSystemId: sysTrade.systemId,
        path: [sysTrade.systemId],
        pathIndex: 0,
        mission: 'attack',
        departureTime: state.timeMs,
        arrivalTime: state.timeMs + 30000,
        totalDistance: 0,
        speed: 10,
        fuelCost: 0,
        recallLockedAfterTime: state.timeMs + 15000,
        isReturning: false,
        status: 'orbiting',
      };
    }
  }

  // 6. Compute Net Trade Value Reaching Capital per Player
  for (const [playerId, pTrade] of Object.entries(state.tradeStates)) {
    let playerCollected = 0;
    let playerLost = 0;

    for (const route of pTrade.routes) {
      if (route.originPlanetId === route.destinationPlanetId) {
        playerCollected += route.tradeValue;
        continue;
      }

      // Determine highest piracy risk encountered along route
      let maxPiracyOnRoute = 0;
      for (const sysId of route.pathSystemIds) {
        const sysInfo = state.systemTrade[sysId];
        if (sysInfo && sysInfo.piracyRisk > maxPiracyOnRoute) {
          maxPiracyOnRoute = sysInfo.piracyRisk;
        }
      }

      const lossRatio = Math.min(0.70, (maxPiracyOnRoute / 100) * 0.50);
      route.piracyLoss = Math.round(route.tradeValue * lossRatio * 10) / 10;
      route.collectedValue = Math.max(0, Math.round((route.tradeValue - route.piracyLoss) * 10) / 10);

      playerCollected += route.collectedValue;
      playerLost += route.piracyLoss;
    }

    pTrade.totalCollectedTV = Math.round(playerCollected * 10) / 10;
    pTrade.totalLostTV = Math.round(playerLost * 10) / 10;
    pTrade.lastUpdateMs = state.timeMs;

    // 7. Deposit Resource Yields into Homeworld based on Trade Policy
    const config = TRADE_POLICY_CONFIGS[pTrade.policy] || TRADE_POLICY_CONFIGS.energy_wealth;
    const hoursElapsed = deltaMs / 3600000;
    const convertedTV = pTrade.totalCollectedTV * hoursElapsed;

    const playerPlanets = Object.values(state.planets).filter((p) => p.ownerId === playerId);
    const homeworld = playerPlanets.find((p) => p.isHomeworld) || playerPlanets[0];

    if (homeworld && convertedTV > 0) {
      // Fuel deposit
      if (config.fuelRatio > 0) {
        const fuelGain = convertedTV * config.fuelRatio;
        homeworld.resources.fuel = Math.min(
          homeworld.storageCap,
          homeworld.resources.fuel + fuelGain
        );
      }
      // Crystal deposit
      if (config.crystalRatio > 0) {
        const crystalGain = convertedTV * config.crystalRatio;
        homeworld.resources.crystal = Math.min(
          homeworld.storageCap,
          homeworld.resources.crystal + crystalGain
        );
      }
      // Cultural Unity deposit (Phase 17)
      if (config.unityRatio > 0 && state.traditions && state.traditions[playerId]) {
        const unityGain = convertedTV * config.unityRatio;
        state.traditions[playerId].unity += unityGain;
      }
    }
  }
}
